### ISSUE TITLE
Support Monaco >= 19.0.0

### ISSUE THREAD

**Issue by ianberdin** [convergencelabs/monaco-collab-ext#3]
I ran on monaco 0.19.0 and cursors doesn't work:

“"cssMode.js?db4f:54 Uncaught (in promise) TypeError: monaco.languages.registerSelectionRangeProvider is not a function””

It’s may help: Monaco-editor did breaking changes: getConfiguration() is replaced by getRawOptions(), which returns the passed in editor options.

**Comment by mmacfadden** [comment]
@ianberdin Thanks for reporting the issue, I am taking a look at it now and will see if we can provide a quick fix.

**Comment by CGNonofr** [comment]
https://github.com/convergencelabs/monaco-collab-ext/pull/4

**Comment by mmacfadden** [comment]
We pushed 0.3.0 which should address this issue.
