### ISSUE TITLE
Support default export?

### ISSUE THREAD

**Issue by cktang88** [convergencelabs/monaco-collab-ext#6]
I have a project using this with Webpack and React.

Currently I'm importing by:
```js
import * as MonacoCollabExt from "@convergencelabs/monaco-collab-ext";
```
This was counterintuitive, and took me a while of debugging Webpack errors to figure out.

I think it's more intuitive to import with 
```js
import MonacoCollabExt from "@convergencelabs/monaco-collab-ext";
```
or even
```js
import { MonacoCollabExt } from "@convergencelabs/monaco-collab-ext";
```

**Comment by mmacfadden** [comment]
Thanks for commenting! I might be a a bit confused here, and I have to validate this tomorrow (I am on a mobile device now with out access to the code), but wouldn't instead you just want to do something like this:

```
import { RemoteCursorManager, EditorContentManager } from "@convergencelabs/monaco-collab-ext";
```

The `MonacoCollabExt` namespace is really only used if you are hot-linking using a script tag with the `umd` distribution.  We could probably update the documentation to make that more clear.
